export interface Store {
    Store_ID: number,
    Store_Trademark?: any,
    P_Code?: any,
    P_Name: string,
    C_Code?: any,
    C_Name: string,
    Post_Code: string,
    Store_Name: string,
    Car_Brand: string,
    Store_Principal: string,
    Contact_Way: number,
    Order_Integral: number,
    Branch_ID: number,
    Branch_Name: string,
    Scen_str: string,
    Nick_Name: string,
    Register_Integral: number,
    Max_Integral: number,
    Store_Address: string,
    Longitude: string,
    Latitude: string,
    Is_Use: boolean
}